### ISSUE TITLE
Audible source no longer parsing properly

### ISSUE THREAD

**Issue by DutchyOven** [seanap/Plex-Audiobook-Guide#10]
Instead of parsing out the author and narrator etc its putting all the information on the author line like this...

`Author: By: John Doe Narrated by: John Doe Series: Example Book, Book 3, Example Book, Book 3 Length: 7 hrs and 53 mins Categories: Teen & Young Adult, Science Fiction & Fantasy 				 				 				 				 				 4.9 out of 5 stars`

instead of 

`Author: John Doe`

It's adding the information into the other fields except for Genre and Book Series/Number, that's being kept blank. I've updated it to the most current 11/8.

I set it up a few months ago and all has been working great until I tried today. Wonder if Audible changed the site configuration and its scraping incorrectly now?

**Comment by seanap** [comment]
I'm getting the same thing. Looks like audible changed something on their end.

**Comment by seanap** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/17012946/98883595-6f6df380-245c-11eb-9907-cc64f132ea8c.png)
