### ISSUE TITLE
Link in README Takes You to Tech Support Scam

### ISSUE THREAD

**Issue by blindgoat** [seanap/Plex-Audiobook-Guide#112]
In the [Backing up Your Audible books](https://github.com/seanap/Plex-Audiobook-Guide?tab=readme-ov-file#backing-up-your-audible-books) section of the README, it says "In the mean time please check out this awesome guide here: " and links a checkthebechmarks article that redirects you to several different scam / virus tech support sites.

**Comment by seanap** [comment]
Yikes, looks like that domain was sold and the guide removed. I removed the link.  Thank you for letting us know.
