### ISSUE TITLE
[Unknown Artist] and [Unknown Album] on 436 track book

### ISSUE THREAD

**Issue by retrodans** [seanap/Plex-Audiobook-Guide#16]
I have gone through the process of tagging and importing a rather large book (436 tracks).  But when I ask Plex to scan it, it gives me a lot of albums, all appear to have a similar issue of: [Unknown Artist] and [Unknown Album]

All other albums I have imported appear fine though.  Is there a known issue with audiobooks with this many tracks?  Also, are there possible solutions too?

Thanks for your help,
Dan

**Comment by seanap** [comment]
The number of tracks shouldn't be an issue, I have a few books with a couple hundred tracks that work just fine.  Which book are you working on, is this book on Audible?

When plex shows a lot of albums for the same book it's sometimes that the Track tag isn't set, or there is something in the Disc tag, or the Album tags are different.  If all the tags look good, then you may just have to Merge the albums in Plex.

**Comment by retrodans** [comment]
Thanks, sorry took me a while to reply, I wanted to try a few things after your comment.  It turns out that the files were .m4a files, and once I converted them to mp3 (then went through the tagging steps) it all appears to work fine now, which is great.

Thanks for the steps and help.

**Comment by retrodans** [comment]
I am noticing some other issues, but before I investigate, are there recommended formats to avoid do you know (this one was m4a, but I am also seeing some oddities with a wma file, but may be unrelated)

**Comment by seanap** [comment]
I would recommend sticking to chapterized m4b's.  Single file books dramatically speed up plex's scan time.  

I have a few m4a and wma books that I don't have any issues with, plex/mp3tag works just fine on them.
