### ISSUE TITLE
Matching Chapter Names

### ISSUE THREAD

**Issue by tylernguyen** [seanap/Plex-Audiobook-Guide#19]
Is there anyway to match the track title with the chapter names?

Say: Prologue: "xxx", Chapter 1: "xxx", 2, 3 and so on.

I don't mind doing this manually. Thought automated would be great.

Right now, it tags every track at 01 and onward. This bugs me as some books starts with a prologue so chapter 2 would be mislabled as 01.

**Comment by seanap** [comment]
There definitely isn't an automated way to get the actual chapter title (": xxx"). We would need a repository that had all the chapter data that we could scrape.  Musicbrainz _might_ have a handful of popular books chapter titles but I haven't found a consistent source.  If you are ripping all of your own books that you own from Audible there is a way to use Audible-cli to use the API to obtain the chapter metadata https://github.com/mkb79/audible-cli/blob/master/utils/update_chapter_titles.py

What you could do is tag the tracks (ctrl+k) starting at 0.  Then you can run a simple action script that sets the Title to "Chapter %track%".  Then you would have to rename "Chapter 00" to "Prologue" but that beats manually renaming all the other chapters.
![image](https://user-images.githubusercontent.com/17012946/117558133-5f6c5080-b048-11eb-9a05-21b3e00e373c.png)

**Comment by tylernguyen** [comment]
> Then you would have to manually rename "Chapter 00" to "Prologue" but that beats manually renaming all the other chapters.

Sorry, I'm quite new to MP3Tag. Which button would allow me to manually do this?

**Comment by seanap** [comment]
It's the TITLE tag.
![image](https://user-images.githubusercontent.com/17012946/117558291-0c939880-b04a-11eb-8a09-ff81d746e607.png)

**Comment by tylernguyen** [comment]
> 
> 
> It's the TITLE tag. If you dl the github repo all my settings and customizations are included, and if you load them your mp3tag should look like mine.
> 
> ![image](https://user-images.githubusercontent.com/17012946/117558291-0c939880-b04a-11eb-8a09-ff81d746e607.png)

What about for single file audiobooks?

I only see the option for one chapter.

Again, apologies for my inexperience with MP3Tag.

**Comment by seanap** [comment]
Go to settings > Tags > Advanced > Tick "List chapters as separate files" then re-add the m4b into mp3tag.

![image](https://user-images.githubusercontent.com/17012946/117558382-e8848700-b04a-11eb-8a05-ce5576d375eb.png)

**Comment by tylernguyen** [comment]
It works now! Thank you.

I assume MP3 has to be converted into M4B before that could work?

**Comment by seanap** [comment]
Like a single MP3? No, you would need to run it through inAudible and create chapters based on silence, then convert all the mp3 tracks into an m4b, then open it in mp3tag and change the chapter title.

If you have a folder with multiple mp3's, then you can just change the title like I show in the picture [here](https://github.com/seanap/Plex-Audiobook-Guide/issues/19#issuecomment-835629839)
