### ISSUE TITLE
Could you indicate that this is primary Windows based?

### ISSUE THREAD

**Issue by Tharic99** [seanap/Plex-Audiobook-Guide#2]
This is a phenomenal guide you have here. Thank you so much for putting this all together and sharing it out. So as an Ubuntu user, this took me a moment to fully realize that mp3tag is only a Windows/Mac based app. So I had gone through reading in detail everything, formulated a plan of attack only to realize it wouldn't work for me as written. 

I'm trying to see how far I can get using puddletag to do the same thing as mp3tag, but puddletag is new to me.

If anyone has any recommendations though, feel free to share them!

Thanks

**Comment by seanap** [comment]
puddletag supports using Mp3tag’s tag sources. To use them create the directory ~/.puddletag/mp3tag_sources and place any tag sources in there. If everything went okay, they’ll be loaded when you start puddletag. In the Tag Sources window they’ll be listed with ‘[M]’ appended to the filename.

Mp3tag can also be run with Wine on ubuntu.

**Comment by WeisseTeetasse** [comment]
So does this work on a headless linux server at all?

**Comment by seanap** [comment]
Plex, Plex Audiobook Agent, my little helper script, and booksonic all work on headless linux.

Mp3tag can work via CLI but it's windows.  It looks like there may be a docker for Puddletag, not sure if that is able to be run in the Terminal.  If you are able to get it to work let me know.

**Comment by pquodling** [comment]
I love the look of this, very thorough - but - I am running a mac (and several Raspberry pis) - no windows machines - so no mp3tag - apparently it can normally be run under Wine, but there is also a problem running Wine Apps under MAcos Catalina. 

Other Options?

**Comment by seanap** [comment]
I don't have a mac to test anything, but if you can't get Wine to work, there's always [VirtualBox](https://osxdaily.com/2015/03/25/install-run-windows-10-mac-virtualbox-os-x/)

If you find a mac alternative let me know and I can add it.

**Comment by Diegus83** [comment]
For the mac users out there, there is a version of mp3tag here working under Wine and I had luck running it in macOS High Sierra. If you are running the latest macOS (Catalina) you are going to need a virtual machine with a supported OS.

As for the files you are suppose to replace, the path would be:
`Right click on mp3tag.app, Show Contents`

and then navigate to
`/Contents/Resources/wineprefix/drive_c/users`

**Comment by WeisseTeetasse** [comment]
So how integral is Mp3tag to the whole process. I am failing to understand the chain here. Will this still work without Mp3Tag?
What do i need to change for Puddletag?

**Comment by seanap** [comment]
I have a script written for Mp3tag (which should also work for Puddletag) that will scrape audible and tag your audiobooks in a standardized way that matches the Plex Audiobook Agent. Without tagging your audiobooks the Agent has a hard time matching books.  I suppose you could tag everything manually if you want.

**Comment by marcodamm** [comment]
Works for me on Manjaro with Mp3tag on Wine. Thanks for all the work you put into this @seanap :+1:

**Comment by Xirg** [comment]
> Plex, Plex Audiobook Agent, my little helper script, and booksonic all work on headless linux.
> 
> Mp3tag can work via CLI but it's windows. It looks like there may be a docker for Puddletag, not sure if that is able to be run in the Terminal. If you are able to get it to work let me know.

i created a docker image for puddletag here: https://github.com/Xirg/docker-puddletag
But currently i cant get it to work with your MP3tag sources i suspect its because puddletag have been ported to python3 and the regexp fucktion isn't working properly yet
feel free to fork and or copy the Dockerfile but bear with me, im fairly new to creating Dockerfiles

**Comment by Xirg** [comment]
And if theres any need i also did a docker image for mp3tag that should be working.

https://github.com/Xirg/docker-mp3tag

**Comment by seanap** [comment]
Rabelux added a note to the guide and until there's a cross platform app Xirg's mp3tag docker works for Linux, and either Wine or VirtualBox works for MacOS

**Comment by benhutchins** [comment]
There has been a MacOS-version of mp3tag available for a few months now: https://mp3tag.app/

**Comment by frayedknot** [comment]
Has anyone gotten the audible tag sources to work in Mp3tag under wine? When I try to search with audible, I get an error: 

```
Error connecting to server: www.audible.com

Unable to get an error message for error code: -2146893051
```

**Comment by Diegus83** [comment]
They used to work for me in Mojave when I could still run it. Never tried again since updating to Catalina.

**Comment by frayedknot** [comment]
I should have specified that this is on Linux.

**Comment by rabelux** [comment]
Have a look at https://github.com/seanap/Plex-Audiobook-Guide/discussions/67

**Comment by seanap** [comment]
> I should have specified that this is on Linux.

This isn't a solution for mp3tag, but check out the beets.io audible plugin, works really well under Linux https://github.com/seanap/beets-audible

**Comment by frayedknot** [comment]
https://github.com/seanap/beets-audible works fantastic under linux and was pretty easy to get set up

**Comment by Larosen** [comment]
> This isn't a solution for mp3tag, but check out the beets.io audible plugin, works really well under Linux https://github.com/seanap/beets-audible

How do I get this on synology docker? I can find seanap/auto-m4b under registry and setup worked fine. But nothing else of yours can be found at all. I'd also like to use Beets-Audible, since concurring mp3 into m4b is only half of the job :D

I guess your beets-audible must be available here, to be available on synology. https://registry.hub.docker.com/r/seanap/auto-m4b/

**Comment by seanap** [comment]
I don't have a synology so I can't help you there.  The beets.io has two components to it, the beets.io docker, and the audiobook plugin.  The way my beets fork works is the standard docker gets installed first then the config gets overwritten and the audible plugin and dependencies get installed.  There isn't a docker that has everything installed available on the hub. You will either need to use the standard beets.io docker img from the hub and then ssh into your synology to manually add the audible plug in and config, or just see if you can ssh into your synology and install via cli as outlined in my install instructions. 

Maybe following the original instructions https://github.com/Neurrone/beets-audible would work?
