### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by rabelux** [seanap/Plex-Audiobook-Guide#20]
Little offtopic:
Is there a reason the audible-sources are split into two different directories?
![image](https://user-images.githubusercontent.com/16120882/119667513-a7f08000-be36-11eb-9e58-05c42e7a55af.png)
When downloading the zip on windows all files end up in the same spot, as intended I guess (although there are case differencies)
Is this some submodule/subtree stuff?

Thank you for your guide btw, I'm currently in the process of setting everything up.

**Comment by seanap** [comment]
You're welcome!

All files in the same spot is intended.  I tried to fix the github folders a few times but it always separated it out like that.  Not sure how to fix it.

**Comment by rabelux** [comment]
Fixed with #21. I also thought adding a note mentioning Windows as the targeted system helps as I ran into the same issue as the poster of issue #2.

**Comment by seanap** [comment]
Thanks!
