### ISSUE TITLE
Could you please help me with one part of the setup?

### ISSUE THREAD

**Issue by hvddrift** [seanap/Plex-Audiobook-Guide#22]
The instructions have the following:

`%APPDATA%\Mp3tag\data\action\1 m4b.mta Update lines 3, 15, 22 with the path to your Plex \Audiobook folder`

I have tried several variations and cannot seem to get the correct syntax.

MP3tag can see my temp folder
![Mp3tag_2021-06-14_21-54-11](https://user-images.githubusercontent.com/972926/121888264-1ef4a680-cd5b-11eb-9c15-de722b08f910.png)

My folders are on my Synology drive. Could you please show me the correct way to put this folder into the notepad++ instructions?

What part of this line do I change: 
`1=X:\\Audiobooks\\%albumartist%\\%series%\\%year% - %album%[ '['%series% %series-part%']']\\%album% (%year%)[ '['%series% %series-part%']']`

To point to this folder?
S:\tempab
another way file explorer shows this folder is like this:
![explorer_2021-06-14_21-51-56](https://user-images.githubusercontent.com/972926/121888036-d89f4780-cd5a-11eb-80bb-be20602c27e3.png)

Thanks in Advance

**Comment by seanap** [comment]
You have your Syncology nas mounted and mapped to "S:"?  You may need to "map network drive" in windows.

**Comment by hvddrift** [comment]
Hazar, that works. Thank you
