### ISSUE TITLE
Synology DSM Version 7 and Changes in Plex Use of Plugins

### ISSUE THREAD

**Issue by jalanmac** [seanap/Plex-Audiobook-Guide#27]
I upgraded my Synology DSM to Version 7 and thanks to Plex Member ChuckPa I was able to successfully update my Plex to a supported version of Plex. Everything except for the recognition of new audiobooks is working fine in Plex but unfortunately during the Plex upgrade it disabled the audiobook plugin that you have created and which is included in your software. I found a post for other Plex plugins on DSM 7 which indicated that plugins may still work if they are copied into the plugin directory in the upgraded Plex environment so I did that via SSH - but unfortunately the audiobook plugin doesn't seem to be working as new audiobooks added to my library are not being recognized by Plex. Do you intend to upgrade your applications to support Plex on DSM 7 by any chance? Thanks in advance for what you have created and any support or insight you may be able to provide.

**Comment by seanap** [comment]
Hey, plug-ins still work. Sounds like you may have a file or folder permissions issue.

**Comment by jalanmac** [comment]
I wondered the same thing so I went to the Plex forum and got support to ensure that my permissions were correct but the plugin still won't recognize in my installation:

https://forums.plex.tv/t/i-cant-add-update-plugins-agents-metadatas-with-dsm7-help/732576/10

I am using the newest Plex beta release, although this issue has been existing since my upgrade to 7
![image](https://user-images.githubusercontent.com/38288166/128643505-2e086f2c-1850-45ae-b7ce-45f26b658660.png)

I looked in the Plex Media Server.log for audiobooks bundle and found the following lines:
Aug 08, 2021 10:17:24.289 [0x7fb06177ab38] DEBUG - Starting plug-in /var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/Audiobooks.bundle.
Aug 08, 2021 10:17:24.290 [0x7fb06177ab38] DEBUG - Perfect cache hit, we don't need to start [com.plexapp.agents.audiobooks] yet.

Can you think of anything else I could do to troubleshoot?

Many thanks in advance!

**Comment by seanap** [comment]
Hey I found a forum response that they were able to get scanners and agents to work with DSM 7.

`After users on Reddit confirmed that it still works, I was able to use Hama and ASS on Plex in DSM 7.

Hama is an agent plugin, ASS is a scanner.

Just install both of them in /volume1/@apphome/PlexMediaServer/Plex Media Server under the Plug-ins and Scanners folders respectively. Make sure to change the permissions so the user PlexMediaServer has read and write access to them.`

https://forums.plex.tv/t/solved-dsmv7-how-to-update-plugins-agents-scanners/700715/12

**Comment by seanap** [comment]
### To Summarize:

1. Plex Product and Engineering teams deprecated Plug-ins over 2 years ago
2. Plex/web team, at product direction, removed User-Facing plug-ins.
3. DSM 7 mandated a storage structure change which removed the “Plex” shared folder.

### What does this mean?

- Plug-ins must be installed via the SSH command line – If used.
- Move the .bundle folder to /volume1/@apphome/PlexMediaServer/Plex Media Server/Plug-ins
- chmod/chown to change permissions so the user PlexMediaServer has read and write access

If anything else changes we can open this issue back up, but for now there is nothing more I can do.
