### ISSUE TITLE
Plex Agent Renaming Album titles

### ISSUE THREAD

**Issue by Abstain-Senate-Retype** [seanap/Plex-Audiobook-Guide#32]
A recent install of plex docker on unraid and audiobook agent. Shortly after scanning a bunch of my books album titles started getting changed to - "No-No Boy" by John Okada [2018]. Half of my audiobook library has had its name changed. When I look at the log I see:
Sep 20, 2021 19:21:11.021 [0x14b131ef8b38] Error — Exception loading item '(BOOK NAME)' from bundle: invalid type specifier

Picture attached is a book with the issue

![image](https://user-images.githubusercontent.com/90658534/134097256-b451338d-c61c-4ded-b4b4-80947e48faa7.png)

**Comment by seanap** [comment]
There is an issue with the new plex release that breaks the agent.  We're working on a fix.  In the mean time you can roll back to 1.24.2

**Comment by Abstain-Senate-Retype** [comment]
Ok, thank you for such a quick reply. I will do just that
