### ISSUE TITLE
Agent not populating media in Plex

### ISSUE THREAD

**Issue by soricesg** [seanap/Plex-Audiobook-Guide#33]
Recently started noticing Audiobook media not being populated by the agent, logs full of 
Exception loading item 'BOOKNAME' from bundle: invalid type specifier

It seems some other users on [Reddit](https://www.reddit.com/r/PleX/comments/ps04ix/audiobook_agent_not_working_for_me/) are seeing the same behavior 

Please let me know if I can provide more info

**Comment by seanap** [comment]
There was a Plex bug in 1.24.3 that broke the agent.  The latest update has fixed it, please update to the latest PMS 1.24.4.

Also check out the upgraded audiobook agent https://github.com/djdembeck/Audnexus.bundle

**Comment by soricesg** [comment]
Awesome thanks for the info! Updating now!
