### ISSUE TITLE
How to update automatic naming of album?

### ISSUE THREAD

**Issue by thew1se** [seanap/Plex-Audiobook-Guide#4]
Hi

Thanks again for an awesome job!  I've been using it regularly over the last couple of days with no problems.

One preference I have for my library is that after the meta data loads using the import from MP3TAG, im not bothered to have it import anymore with the metadata agent.  I will handle it manually from that point forward.

That being said, I have configured plex as such. - no issues.

What I would like to do is have the 'Album' and 'Album Sort' fields named slightly differently so they list in plex with all books together and in order:

"SeriesName SeriesBook# - Book Title"
For example:
![image](https://user-images.githubusercontent.com/57738712/88611390-eb336400-d056-11ea-8ad6-9a8db232c682.png)

I have been doing it manually for each book up to this point before I click the action button.  Everything works great except I had to edit the folder and file naming to eliminate this same info at the end of the title.

I'm not a programmer so a little detail is required if you're willing to point me in the right direction!

Thanks in advance!

**Comment by seanap** [comment]
The ALBUMSORT tag is already set to `SeriesName SeriesBook# - Book Title` When creating the Audiobook library make sure to set the sorting to "Name" https://i.imgur.com/ZCguwkb.png

You can change the way the ALBUM tag is set in the .src file to match ALBUMSORT if that's your preference.

The file/folder names can be modified in the custom action script.  Change the 'Format Value' to your liking.

**Comment by thew1se** [comment]
Thanks.  This is a little over my head.  I had a look at the source file, but can't seem to see where ALBUM or ALBUMSORT are applied variables to make their fields as expected.

**Comment by seanap** [comment]
I have a fundamental disagreement with how you are trying to label the ALBUM tag.  The ALBUM tag is meant as "Book Title", so when you modify this tag you are changing the Title of the book, which means the Plex Audiobook Agent will now have a much harder time trying to match Titles.  

I like to think of Audiobooks like Movies.  You don't name your movies "Fast and Furious 2 - 2 Fast 2 Furious" do you?  I let the TMDB name my movies with the exact movie title, and use collections or sorttitle to keep series grouped and in order.

In my Audiobook library all series are grouped and in order based on the ALBUMSORT tag.  I would fully agree that Plex needs to handle album series/collections better, frankly Plex needs to do a lot of things better, but I disagree with modifying the title of the book in the tags.

That said if you want tag ALBUM as ALBUMSORT you can give this .src a try. [Audible.com#thew1se.zip](https://github.com/seanap/Plex-Audiobook-Guide/files/5041106/Audible.com.thew1se.zip) 
Then you will have to change all the Format Values in the action script to your liking.  You'll need to update the _FILENAME, COVER, and Export Filename's.  

For example:
From: 
C:\path\to\Audiobooks\%albumartist%\%series%\%year% - %album%[ '['%series% %series-part%']']\%album% (%year%) ['['%series% %series-part%']' ]- pt$num(%track%,2)
To: 
C:\path\to\Audiobooks\%albumartist%\%series%\%albumsort% (%year%)\%albumsort% (%year%)- pt$num(%track%,2)

**Comment by thew1se** [comment]
Thanks I'll have a look. 

I know it's not perfect but I find my method more user friendly when it comes to displaying artwork, organizing series' in order, and understanding which books are part of which series.  

Ideally in my mind there would be 3 fields for books organized as such. 

1. Universe book #
2. Series book #
3. Book title

The vast majority of books wouldn't use #1 but if you look at series' like Shannara, there are several anthologies within the Shannara universe. 

Ideally it would display as an album with all artwork. 

Regardless, just trying to make it work for Plex until they get audiobooks fully supported.....if that ever happens.  

Thanks again for your awesome work, it's much appreciated.  I'll give this a go.

**Comment by seanap** [comment]
Ah, OK I see what you're trying to do.  Multi-series books are very hard to do automatically, currently this script just takes the first series and ignores the rest.   You can make a custom tag in mp3tag ie. Universe.  Then you can add the %universe% tag to the action script format so that it will put everything in the right folder for you.  That way your folder structure will be the way you want it at least.

I'm not holding my breath for Plex to fully support audiobooks, but hopefully someone will come out with something good.  I'm looking forward to Book Camp, maybe they will be able to solve some of these issues.
