### ISSUE TITLE
%totaltracks% does not work properly 

### ISSUE THREAD

**Issue by milousparks** [seanap/Plex-Audiobook-Guide#45]
Steps to reproduce:

1. Audiobooks with more than one track
2. Try to execute Skript like in the README
3. Error: "Cannot create a file when that file already exist" on second audiofile in the book.

I narrowed it down to the `%totaltracks%` doesn't seem to return a correct value because  the if condition `$ifgreater(%totaltracks%,1, - pt$num(%track%,2),)` in the actions script always returns an empty space.

If i change it to `$ifgreater(2,1,- pt$num(%track%,2),) `  which is always true everything works fine

**Comment by rabelux** [comment]
Fixed by 0526c1be703c08d53d36f5d51b55dceb63692f60?

**Comment by milousparks** [comment]
Yes, indeed, this fixed my issue! Thanks alot
