### ISSUE TITLE
Dropit skips files; shows destination as original folder despite associations set to temp folder

### ISSUE THREAD

**Issue by chuccck** [seanap/Plex-Audiobook-Guide#46]
Can't figure it out but Dropit does not recognize the associations folder setting to copy to the temp folder, it keeps trying to copy it to the same original folder.  Note the G drive is a drivepool drive but that shouldn't matter.  

![image](https://user-images.githubusercontent.com/16928983/145714579-0bb95c06-0f14-44f1-8839-ec6b6eaeebec.png)

![image](https://user-images.githubusercontent.com/16928983/145714604-8f77fa89-4224-4508-b692-3dbaf21f1345.png)

![image](https://user-images.githubusercontent.com/16928983/145714643-5588e65c-9698-4da2-b861-829b6472a76e.png)

**Comment by seanap** [comment]
Looks like it isn't respecting the Destination Folder. In the first pic the "Destination" is the /original folder.

**Comment by seanap** [comment]
Is there a space between the `...audiobook \temp` ?

**Comment by chuccck** [comment]
there is no space, just windows formatting between the k and \

i dont know why the destination is set to original when the associations is set to temp.  cant figure it out

**Comment by seanap** [comment]
In Options > Various there are log files, anything in there?

**Comment by chuccck** [comment]
no additional detail
![image](https://user-images.githubusercontent.com/16928983/145715376-7ce7889f-ce47-404c-99c0-581a2463a178.png)

**Comment by seanap** [comment]
Heh that's not very helpful.

It looks like you have the `BookCopy` profile selected for the `AudiobookCopy` association.  Is the BookCopy profile active?

![image](https://user-images.githubusercontent.com/17012946/145715676-d1545892-b770-44e2-813f-5ddd62e72310.png)

**Comment by chuccck** [comment]
yeah i do 

![image](https://user-images.githubusercontent.com/16928983/145715935-226db6fc-9b31-4092-80e0-fe025ff87ade.png)

**Comment by seanap** [comment]
Have you tried quitting DropIt and restarting it?

**Comment by chuccck** [comment]
yep no dice, ill try restarting the computer

**Comment by chuccck** [comment]
no change after a restart

**Comment by seanap** [comment]
The drivepool drive shouldn't be an issue (I'm using a MergerFS pool with no issues) but for testing can you recreate another test profile and use only local folders?  Doesn't have to be anything fancy, maybe just set it up to copy a .txt file from one folder to another to make it easy.  

From the settings you have provided nothing looks wrong, so I'm kinda stumped.

**Comment by chuccck** [comment]
shoot, that worked....

![image](https://user-images.githubusercontent.com/16928983/145716669-19316d7b-9ce7-4830-a0db-5acddd7403f2.png)

![image](https://user-images.githubusercontent.com/16928983/145716683-edc4a75f-9a6f-4928-a629-6f2313afe3f0.png)

![image](https://user-images.githubusercontent.com/16928983/145716693-37895a97-2d21-49fa-a6a8-55efca60bdc5.png)

**Comment by chuccck** [comment]
im going to reset the bookcopy profile with those local folders and see if it works with an audiofile now

**Comment by chuccck** [comment]
something is borked in the bookcopy profile:

![image](https://user-images.githubusercontent.com/16928983/145716898-701d1d28-0053-4536-958b-2f105686a9cd.png)

**Comment by chuccck** [comment]
i restored your from you backup settings

**Comment by seanap** [comment]
Are you finding that if you had a fresh install of Dropit and built up the profile/associations from scratch it works but if you use my supplied backup something is broken?

It's been a long time since I've updated dropit maybe a new release broke my old backup settings?

**Comment by chuccck** [comment]
i will try that.  is there anything in the backup settings we have not done here other than the file associations?

**Comment by seanap** [comment]
Here are all my settings:
![image](https://user-images.githubusercontent.com/17012946/145717218-32d09850-2c69-4a49-a08d-a4777d200dc3.png)
![image](https://user-images.githubusercontent.com/17012946/145717233-b89377b0-948f-4e04-a811-3b5bd93e3219.png)
![image](https://user-images.githubusercontent.com/17012946/145717246-342516d8-ee46-4d69-82fb-c7c195834892.png)

**Comment by chuccck** [comment]
associations settings too please?

**Comment by seanap** [comment]
![image](https://user-images.githubusercontent.com/17012946/145717375-a73afcfd-bb9a-4e81-9fd4-9b78fd85436c.png)

**Comment by chuccck** [comment]
rebuilding it worked.  do i want those text and covers to copy/move?  i am not seeding

![image](https://user-images.githubusercontent.com/16928983/145717460-5f2b9f6d-26da-4a3f-8514-2ecc3465f45f.png)

**Comment by seanap** [comment]
After DropIt moves the files into the temp folder that mp3tag watches, I have mp3tag tag the files and it will export the cover to the new archive folder (that plex looks at).  It also outputs a reader.txt and desc.txt but those are only used for booksonic.

You shouldn't need to copy any of those text and cover files since the cover will be readded and those txt files won't be used by anything.

**Comment by chuccck** [comment]
Thanks for your help.  I need to step away from the computer for the day
but I have questions on that automated process.  Is there a better way to
ask you then bogging your GitHub down with issues ?

**Comment by seanap** [comment]
The automated process I have set up is for two things:

1. To preserve seeding files so my originals are untouched
2. To auto convert mp3's to a chapterized m4b

They are completely optional, for example you can just set up mp3tag to look at your original folder and process your books directly.

I don't mind reporting issues like you did here, this is very helpful for everyone that comes by in the future.  For discussions feel free to open a new thread in the Discussions tag.   You can also find me and other likeminded folks in the BookCamp discord server.
