### ISSUE TITLE
Plex album artist (author) sort mixing between first name and last name

### ISSUE THREAD

**Issue by chuccck** [seanap/Plex-Audiobook-Guide#48]
struggling to figure out why some of these books are sorted by first name and some by last name.  Ive looked at the tags and the plex info and they all have the same author name

![image](https://user-images.githubusercontent.com/16928983/146263175-f8f4d88c-0c66-4710-bae3-b8f71b261437.png)

![image](https://user-images.githubusercontent.com/16928983/146263245-8eca1c7b-cea2-4015-a3f9-5c3e9d1f1d78.png)

**Comment by seanap** [comment]
Likely because you have "Sort: Last Name, First" selected in the agent settings, but the agent couldn't auto match the artist.
![image](https://user-images.githubusercontent.com/17012946/146264188-dbc53ca5-151b-4cc1-ab56-5588b710aade.png)

Go to an artist that isn't sorted Last, First and see if its matched

![image](https://user-images.githubusercontent.com/17012946/146264456-d695958c-71c2-4d86-ab2c-31d9fab6bba3.png)

**Comment by seanap** [comment]
For a point of reference not all artists will match, Audible doesn't have artist profiles for everyone.  For me 300/2400 artists are unmatched.

**Comment by chuccck** [comment]
awesome tips, thanks for the help!

**Comment by seanap** [comment]
If I can add one more unrelated tip, I found with the way plex currently works it's easier to keep a single artist in the ALBUMARTIST tag.  This is absolutely personal preference, but there are some artists who do a lot of collaborations that I like to keep all in the same Artist .

The book you have with `Ken Blanchard, Spencer Johnson` in Mp3tag I just default to picking the first artist that Audible lists and keeping only that as the ALBUMARTIST.  That is why in mp3tag I put all artists, editors, translators, etc in the ARTIST tag, so all artists are still searchable but they just show up on the track level not the album level. 

Probably not a big deal with that book in particular but for books by J.N. Chaney it can get a bit ridiculous.

**Comment by chuccck** [comment]
Thanks that's helpful
