### ISSUE TITLE
Mp3tag alternative?

### ISSUE THREAD

**Issue by Neurrone** [seanap/Plex-Audiobook-Guide#54]
Hi,

I'm wondering if there's any other way of achieving the automatic tagging functionality besides using mp3tag?

For example, I'm wondering if a custom Beets plugin would be able to do this.

**Comment by rabelux** [comment]
Your topic sounds like more like a discussion, so maybe transfer it to https://github.com/seanap/Plex-Audiobook-Guide/discussions?
