### ISSUE TITLE
"Sorry, no entries are matching your search criteria."

### ISSUE THREAD

**Issue by JohanSF** [seanap/Plex-Audiobook-Guide#6]
To reproduce:
Click Next in this dialog:
![image](https://user-images.githubusercontent.com/6782603/89465903-30504800-d773-11ea-9104-364e22473755.png)
It happens with audiobooks that I have already successfully processed a couple of days ago.

Perhaps Audible has changed something on their site?

**Comment by ch1ma3ra** [comment]
I'm seeing the same behaviour here too

**Comment by seanap** [comment]
I'm seeing the same thing, looks like Audible changed something.

**Comment by seanap** [comment]
Resolved.  Looks like Audible changed how they handled the ASIN value, I updated the script to point it at the new location and it seems to be working now.

**Comment by thew1se** [comment]
Can you advise what we need to do to resolve on our end?  I believe just download and replace the Audible.com#search by Album.src file???

**Comment by ch1ma3ra** [comment]
> Can you advise what we need to do to resolve on our end? I believe just download and replace the Audible.com#search by Album.src file???

Yep, that's all you need to do - works fine for me now 👍

**Comment by thew1se** [comment]
Since this fix, I've had a serious issue where once MP3tag opens and downloads data, if I try to edit any of the metadata, the file gets corrupted and can no longer be edited or listened to. 

Anyone else having this problem?  

I tried reinstalling my mp3 tag but keeping the appdata so I didn't have to go through the setup process again. But reluctant to redo the whole thing from scratch.

**Comment by ch1ma3ra** [comment]
> Since this fix, I've had a serious issue where once MP3tag opens and downloads data, if I try to edit any of the metadata, the file gets corrupted and can no longer be edited or listened to. When the problem occurs, the error I get is:
> 
> _File "filename" cannot be opened for writing._
> 
> Anyone else having this problem?
> 
> I tried reinstalling my mp3tag but I kept the appdata during the uninstall process so I didn't have to go through the seanap setup process again. Reluctant to redo the whole thing from scratch since I've updated my folder structure.
> 
> It didn't fix the problem.
> 
> Edit: I should add that this doesn't happen to all books. I just did the Temeraire Series and 1 of 9 books was affected in this series. Also, I cant be 100% sure yet, but I think this is an issue when editing multiple books in mp3tag. I've done several individually and haven't had the issue. It seems to only occur for series'.....so far.

I've not had this problem, been working fine for me (done both series and individual books)
