### ISSUE TITLE
Audible source doesn't show up in Mp3tag

### ISSUE THREAD

**Issue by danseitz** [seanap/Plex-Audiobook-Guide#7]
I copied the SRC file into the data directory (C:\Users\user\AppData\Roaming\Mp3tag\data) and restarted Mp3tag, but it's not showing up in sources (all I see are freedb and freedb local). Is there some other step to import the SRC file?

**Comment by seanap** [comment]
Is it in the `sources` folder? `C:\Users\user\AppData\Roaming\Mp3tag\data\sources`

**Comment by danseitz** [comment]
That was the issue, thanks! I think I was looking at the ini path. Sorry to bother and thanks for the help!
