### ISSUE TITLE
audible

### ISSUE THREAD

**Issue by kcmccombs** [seanap/Plex-Audiobook-Guide#73]
audible finding any matches or not reaching audible web site can someone help with this thanks.

**Comment by seanap** [comment]
What region are you in? Sometimes folks in Australia for example have a hard time going to the audible.com site, their ISP redirects to the au site.

**Comment by kcmccombs** [comment]
I am in the us

**Comment by seanap** [comment]
Can you reach the audible website through your browser? Ex.: https://www.audible.com/pd/How-the-World-Really-Works-Audiobook/0241993075?ipRedirectOverride=true&overrideBaseCountry

Are you on a mac?

You may want to try and re-download the websource script and put it in the mp3tag appdata sources folder https://github.com/seanap/Plex-Audiobook-Guide/blob/master/mp3tag/data/sources/Audible.com%23Search%20by%20Album.src

**Comment by kcmccombs** [comment]
yes
