### ISSUE TITLE
Beets is not renaming chaperts

### ISSUE THREAD

**Issue by Larosen** [seanap/Plex-Audiobook-Guide#75]
Hello,
I have a problem with Beets. When I digitize my audiobooks it sometimes can't capture the individual chapter names and then just calls them "track 1, track 2, etc..." or "name of album 1, name of album 2, name of album 3..."
After processing auto-m4b and launching beets, I select the correct audiobook from the suggestions. 

```
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 1
Tagging:
    Bill Bryson read by Ralph Caspers - A brief history of almost everything: edition for young listeners.
URL:
    https://musicbrainz.org/release/89e2a576-6c3c-4c36-bce2-458d24c543b9
(Similarity: 28.1%) (missing tracks, tracks) (2xCD, 2008, DE, Random House Audio, ISBN: 978-3-86604-963-5)
CD 1
 * A journey into space (140:19) -> A journey into space (2:06) (length)
Missing tracks (47/48 - 97.9%):
 ! Introduction (# 1) (2:22)
 ! Building instructions for a universe (# 2) (3:59)
 ! The Big Bang (# 3) (4:08)
 ! Hello! Glad you made it! (# 4) (2:26)
 ! Listening to the big bang (# 5) (2:19)
 ! Who is out there?                       (# 7) (1:47)
 ! Back on earth (# 8) (3:34)
 ! The earth owl (# 9) (1:37)
 ! What does the earth weigh?                       (#10) (3:00)
 ! How old is the earth?                     (#11) (3:27)
 ! Always nice and slow (#12) (3:08)
 ! Fossil finds (#13) (1:58)
 ! How to date rocks?                  (#14) (1:43)
 ! Bone Age (#15) (2:21)
 ! The mighty atom (#16) (4:07)
 ! A question of chemistry (#17) (3:30)
 ! The periodic table (#18) (2:30)
 ! Radiant elements (#19) (3:07)
 ! Einstein - A genius (#20) (3:22)
 ! Spacetime (#21) (2:42) !
 ! The big picture (#22) (2:49) !
 ! Unfortunate science (#23) (3:06) !
 ! The breaking crust (#24) (2:39)
 ! The fire underneath (#25) (2:38)
 ! The Yellowstone Park (#26) (2:55)
 ! When the earth shakes (#27) (3:23)
 ! Our tiny spot (#28) (4:13)
 ! Water everywhere (#29) (4:40)
 ! Protein soup (#30) (3:27)
 ! Fighting bacteria (#31) (3:46)
 ! Our mini world (#32) (3:15)
 ! What makes us sick (#33) (3:08)
 ! The cell state (#34) (2:52)
 ! How long can you stay?               (#35) (2:26)
 ! Gradually it starts (#36) (2:07)
 ! Out of the sea (#37) (2:55)
 ! Where did we come from ?                  (#38) (1:49)
 ! Journey to the future (#39) (3:30)
 ! The silent monk (#40) (2:56)
 ! One big happy family (#41) (3:42)
 ! The chain of life (#42) (3:10)
 ! Skulls and bones (#43) (3:14)
 ! Lucy (#44) (3:04)
 ! From there to us (#45) (2:25)
 ! Toolmaker (#46) (2:17)
 ! What now ?                                  (#47) (1:51)
 ! And bye!                              (#48) (2:23)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 
```

What do I have to select now, that at the end in Prologue the single chapters are named as suggested above and not "Track1, Track2, ...."?
I have already tried A,U,T without success.

**Comment by seanap** [comment]
Right now the audible beets plug in can only rename separate tracks (not single m4b's), and only if the number of tracks matches the number of chapters. It is very limited right now.

When you use auto-m4b it will generate a chapters.txt file, you can manually edit that file with the chapters, then drop that directory with the m4b and chapters.txt into the /temp/merge folder, next time it runs it will rechapter the file based on the txt file.  It's more manual than I want but it's a relatively easy way to add chapters.  

Another way is to reverse operations, if you have mp3's split by chapters, you can run them through beets first to tag the chapters,  then through auto-m4b to combine, then back through beets to clean up the tags.  This way is also not ideal but those are the only ways with these tools right now.

**Comment by Larosen** [comment]
Thanks for this tip! I cloned the Beeet container and specified a different output folder. With this it is halfway manageable. Even though I still have to reintegrate the author name into the folder afterwards and reduce the audiobook itself back into in the layer. Beets always pushes the audiobook into a folder with the author's name, but auto-m4b doesn't like that.

So it's a bit of manual work, but it's very worth it for some audiobooks!!!
