### ISSUE TITLE
French audible audible.fr

### ISSUE THREAD

**Issue by baloodusudouest** [seanap/Plex-Audiobook-Guide#79]
Hi,

Can you add an audible version for the French audible?
In general the audible.com works, but for some audiobook i cannot find them on all the other audible files

For ex, Frankenstein is available in french
https://www.audible.fr/pd/Frankenstein-Livre-Audio/B00NNZV1V6?qid=1659427779&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=f20cf038-cbbb-4fa0-adfe-62ed184d8867&pf_rd_r=3XX3TEG3CF779R7KNDHB

But  when i search on the mp3tag audible, i cannot find it.

Don't hesite if you need more information.

Thanks!

**Comment by rabelux** [comment]
In case you want to try it yourself, the scripts are located here:
[Plex-Audiobook-Guide/tree/master/mp3tag/data/sources](https://github.com/seanap/Plex-Audiobook-Guide/tree/master/mp3tag/data/sources)

**Comment by seanap** [comment]
Changing lines 17 - 20 in the audible.com source script _might_ be enough, but I found with the German version of audible.de the html code changes the heading names from english to german which would break the scrapper (which is just searching for the english keywords in the html).  If this is the case with audible.fr then you would need to open the source code for a book found on both the .com and .fr side by side and find the `findline` referenced in the english .com src script (for all metadata fields eg. Summary, Artist, Narrator, etc) and update with the french nomenclature.   

```
# src script lines 17 - 20 changes
[Name]=Audible.fr
[BasedOn]=www.audible.fr
[IndexUrl]=https://www.audible.fr/search?ipRedirectOverride=true&overrideBaseCountry=true&keywords=
[AlbumUrl]=https://www.audible.fr
```

**Comment by baloodusudouest** [comment]
oh boy... ok i will try, but what program do you use to read the code? i open the source page of the search page to find the information, but it's hard to find the right line to change and pick. Do you use some program or other or you read the page code on notepad or somethink like that?

**Comment by seanap** [comment]
To view the audible HTML I just use the webbrowser (right click and view page source), to edit the .src script I like using Notepad++ but regular Notepad will work as well.  

Once you change the lines from above in the .src script you should be able to see book results, but the actual tags that it pulls over in the book tag review window may have missing tag values, which is tags have a value and which ones are blank?

**Comment by baloodusudouest** [comment]
is it possible to chat with you to help me? at the beginning at least, once i understand how it's work i think it will be ok...

**Comment by baloodusudouest** [comment]
[mp3tagbug.zip](https://github.com/seanap/Plex-Audiobook-Guide/files/9245529/mp3tagbug.zip)
Here the debug of the french and the english version.
He find the book in both of them, but don't show it in mp3tag for the french version.

**Comment by seanap** [comment]
I took a look and compared the INDEX section in both the .com and .fr HTML and everything looks OK, it doesn't look like anything needed to be modified, I was able to manually go through all the `findinline` text to navigate to the correct section.  Mp3tag says it connects to audible.fr but it keeps saying "No Results".

**Comment by baloodusudouest** [comment]
so it's an index section problem or a album section problem?

**Comment by seanap** [comment]
Got it! I kept missing the space before the : in `Date de publication :` and `Langue :`

I only tested it on "The Martian" but it looks like it pulled all the metadata, I'll upload it so you can try it out and see if it works on your end

**Comment by baloodusudouest** [comment]
i'll try right away!!!

**Comment by baloodusudouest** [comment]
Ok so everything works perfectly well except the serie part, movement and copyright

**Comment by seanap** [comment]
Just updated with a fix for the series-part and movement.

**Comment by baloodusudouest** [comment]
works good now! thanks a lot @seanap !!!!!
