### ISSUE TITLE
1mp3Tag Error Naming and Moving Files

### ISSUE THREAD

**Issue by Ralphman21** [seanap/Plex-Audiobook-Guide#89]
About 25% of the time I use the 1mp3tag to write tags and move to a new folder I receive an error. Its always on the second file of the folder and says that it can not move the file to the destination as the file already exists. Its kind of a pain because now my books are split between two destinations and i have to manually add the first file back. Any suggestions on what is causing this error? Thank you

**Comment by seanap** [comment]
You have to make sure to set the track number, ctrl-k.

**Comment by Ralphman21** [comment]
Thank you
