### ISSUE TITLE
Showing ASIN in mp3tag on Mac

### ISSUE THREAD

**Issue by LeLawnGames** [seanap/Plex-Audiobook-Guide#93]
Do you know how to get a visual of the ASIN in mp3tag? I want to be able to quickly rename my files with the ASIN included so that Plex w/ Audnexus automatically checks for matches but I'm having trouble figuring out how to locate the tag itself within mp3tag.

**Comment by seanap** [comment]
It's a custom tag, you'll need to add it to your tag panel. I don't have a Mac but on pc I just right-click in the tag panel and select customize, then add new.

**Comment by LeLawnGames** [comment]
I have an option to customize my tag panel but ASIN doesn't show up as an optional field. Do you happen to know if there's any other name it might be hiding under inside mp3tag or is it just referred to as ASIN for you in yours?

**Comment by seanap** [comment]
You have to create it

**Comment by seanap** [comment]
![image](https://user-images.githubusercontent.com/17012946/214116540-b42c09d8-3a88-4365-af29-7b93c348ccb1.png)

**Comment by LeLawnGames** [comment]
Oh gotcha, now I understand -- thanks for sharing the image! And for any mac users who follow up on this thread the code for value on mac to find the ASIN is "$metasep(ASIN,\\)"
